### ISSUE TITLE
Mavproxy does not wait/fail for device to be available

### ISSUE THREAD

**Issue by Jaaaky** [ArduPilot/MAVProxy#1062]
Latest version of mavproxy assume connected/device available even if it's not..

I've always been running mavproxy as following for example:
while sleep 0.1; do mavproxy --mav20 --master /dev/serial/by-id/usb-Hex_ProfiCNC_CubeOrange_*-if00 --out udp:127.0.0.1:14550 ; done

Which allowed mavproxy to fail when the device is not available and connect once it's there..
On latest version, it does not fail with "device not found" but opens interactive the shell as if the device is there and then fails with any further command with error ERROR in command []: 'NoneType' object has no attribute 'mav'

It has been working fine on version 1.8.46
