### PR TITLE
Add magical submodule

### PR DESCRIPTION
**Pull request by guludo**
Hi everyone!

This pull request implements the GUI proposed [here](https://www.dronecode.org/news-faq/blogs/2016/08/ardupilot-compass-calibration-redesign-intel-team) with some slight modifications.

Currently, a programmed animation is played showing examples of rotations to be performed while the calibration is running. However. the intention (for a future implementation) is to be able to instruct the user which rotations to do so that the calibration finishes faster, that is, rotations that covers geodesic sections with less hits. I strove to come up with a solution so that those instructions can be easily animated with the current API for the vehicle model.

**NOTE**: I just tested this on Linux, so I think that some fixes might be necessary for other systems.

Best regards,
Gustavo Sousa

### CODE REVIEW

**Comment by guludo** [comment]
Hopefully I can upload a video soon.

**Comment by guludo** [comment]
Link to a demo video: https://youtu.be/aYzwa4ZEIYU

File: MAVProxy/modules/mavproxy_magical/__init__.py [hunk 1]
```diff
@@ -0,0 +1,194 @@
...
+# This file is distributed in the hope that it will be useful, but
+# WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
+# See the GNU General Public License for more details.
+#
+# You should have received a copy of the GNU General Public License along
+# with this program.  If not, see <http://www.gnu.org/licenses/>.
+"""
+Compass calibration helper. This is adapted from Ardupilot's local MAVProxy
+module magcal_graph. Some people read it "magical_graph" at the time of
```
Comment (peterbarker) [inline MAVProxy/modules/mavproxy_magical/__init__.py]: While cute, @tridge might want something a little more descriptive for this module :-)

File: MAVProxy/modules/mavproxy_magical/data/arrow.mtl [hunk 2]
```diff
@@ -0,0 +1,14 @@
+# Magical Arrow Material (c) by Intel Corporation
+#
+# Magical Arrow Material is licensed under a
+# Creative Commons Attribution-ShareAlike 4.0 International License.
+#
+# You should have received a copy of the license along with this
```
Comment (peterbarker) [inline MAVProxy/modules/mavproxy_magical/data/arrow.mtl]: Says a license should be present, which it isn't.

Comment (peterbarker) [inline MAVProxy/modules/mavproxy_magical/data/arrow.mtl]: Are there Open or Free tools available that can manipulate these wavefront data objects easily and well?  I can see several that claim to...

File: MAVProxy/modules/mavproxy_magical/__init__.py [hunk 3]
```diff
@@ -0,0 +1,194 @@
...
+        self.ui_process = multiprocessing.Process(target=self.ui_task)
+        self.update_ui()
+        self.ui_process.start()
+
+    def stop_ui(self):
+        if not self.ui_is_active():
+            return
+
+        self.parent_pipe.send(dict(name='close'))
+        self.ui_process.join()
```
Comment (peterbarker) [inline MAVProxy/modules/mavproxy_magical/__init__.py]: Perhaps we could have something a little more definite in terms of killing the UI process in case of it hanging.  Timeout the join and kill it, perhaps?

File: MAVProxy/modules/lib/wavefront.py [hunk 4]
```diff
@@ -0,0 +1,351 @@
+# Copyright (C) 2016  Intel Corporation. All rights reserved.
```
Comment (guludo) [inline MAVProxy/modules/lib/wavefront.py]: I didn't want to impose an extra requirement to the project and writing a parser didn't look hard, so I just decided on writing my own parser.

Anyway, I just tried to install it with `pip install PyWavefront` as it says [here](https://github.com/greenmoss/PyWavefront) with no success.

File: MAVProxy/modules/mavproxy_magical/data/arrow.mtl (hunk 2 above)
Comment (guludo) [inline MAVProxy/modules/mavproxy_magical/data/arrow.mtl]: I my case, it was very easy to use Blender to load and manipulate them.

Comment (guludo) [inline MAVProxy/modules/mavproxy_magical/data/arrow.mtl]: Yep, makes sense. I used templates from https://creativecommons.org/2014/01/07/plaintext-versions-of-creative-commons-4-0-licenses/ .

Maybe ship them with the project? Is there a way to have setup.py doing that for us? I'm not used to writing python distributions.

Comment (guludo) [inline MAVProxy/modules/mavproxy_magical/data/arrow.mtl]: them = the license file :-)

File: MAVProxy/modules/mavproxy_magical/__init__.py (hunk 3 above)
Comment (guludo) [inline MAVProxy/modules/mavproxy_magical/__init__.py]: I'm ok with that. I'll update the PR later.

**Comment by tridge** [comment]
i'm getting the following error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "build/bdist.linux-x86_64/egg/MAVProxy/modules/mavproxy_magical/__init__.py", line 78, in ui_task
    app.frame = MagicalFrame(self.child_pipe)
  File "build/bdist.linux-x86_64/egg/MAVProxy/modules/mavproxy_magical/magical_ui.py", line 586, in __init__
    self.InitUI()
  File "build/bdist.linux-x86_64/egg/MAVProxy/modules/mavproxy_magical/magical_ui.py", line 641, in InitUI
    sizer.Add(self.Body(self.main_panel), proportion=1, **kw)
  File "build/bdist.linux-x86_64/egg/MAVProxy/modules/mavproxy_magical/magical_ui.py", line 673, in Body
    body.Add(self.InstructionsPanel(parent), proportion=2, flag=wx.EXPAND)
  File "build/bdist.linux-x86_64/egg/MAVProxy/modules/mavproxy_magical/magical_ui.py", line 683, in InstructionsPanel
    self.ref_vehicle = Vehicle(panel)
  File "build/bdist.linux-x86_64/egg/MAVProxy/modules/mavproxy_magical/wxvehicle.py", line 57, in __init__
    kw['attribList'] = (glcanvas.WX_GL_SAMPLES, 4)
AttributeError: 'module' object has no attribute 'WX_GL_SAMPLES'

**Comment by tridge** [comment]
despite the above error, I'm presuming this does work for some people, and I don't want to lose it to bitrot, so I am pushing it in to master as it doesn't do any harm if not used, and has some really great ideas in it

**Comment by guludo** [comment]
Thanks for applying @tridge! :-) I'll try to address the issues in a near future. I believe it would be nice having the vehicle widget on the console UI for systems that support the requirements. We could do that in the future.

**Comment by mday299** [comment]
I only get the WX_GL_SAMPLES error on Ubuntu 14.04, working on 16.04, I love this module!

**Comment by guludo** [comment]
The error regarding `WX_GL_SAMPLES` is due to the fact that it is missing in python-wxgtk2.8, but is present in python-wxgtk3.0. That's why the error happens with Ubuntu 14.04 but not with 16.04. I tried a dirty of falling back to using value for `WX_GL_SAMPLES` (namely `18`) in the occurrence of an `AttributeError`, but then I bumped into other things I used in `magical` missing in `python-wxgtk2.8` - my bad :-P.
