### PR TITLE
macOS: remove deprecated and unused imports

### LINKED ISSUE #1304: graph not working with matplotlib 3.8.0+
The `graph` module is not working with versions of `matplotlib > 3.8.0`

### System

MacBook Pro M1
macOS Sonoma 14.2.1
Python 3.11 (installed from `brew`)

### Example

```bash
STABILIZE> graph VFR_HUD.alt
STABILIZE> Adding graph: ['VFR_HUD.alt']
Process Process-5:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.7/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/homebrew/Cellar/python@3.11/3.11.7/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/rhys/.venv/ros2-3.11/lib/python3.11/site-packages/MAVProxy/modules/lib/live_graph.py", line 58, in child_task
    app.frame = live_graph_ui.GraphFrame(state=self)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rhys/.venv/ros2-3.11/lib/python3.11/site-packages/MAVProxy/modules/lib/live_graph_ui.py", line 22, in __init__
    self.create_main_panel()
  File "/Users/rhys/.venv/ros2-3.11/lib/python3.11/site-packages/MAVProxy/modules/lib/live_graph_ui.py", line 35, in create_main_panel
    from MAVProxy.modules.lib.MacOS import backend_wxagg
  File "/Users/rhys/.venv/ros2-3.11/lib/python3.11/site-packages/MAVProxy/modules/lib/MacOS/backend_wxagg.py", line 7, in <module>
    from matplotlib.backends.backend_wx import error_msg_wx, NavigationToolbar2Wx
ImportError: cannot import name 'error_msg_wx' from 'matplotlib.backends.backend_wx' (/Users/rhys/.venv/ros2-3.11/lib/python3.11/site-packages/matplotlib/backends/backend_wx.py)
```

### Notes

The `error_msg_wx` function is removed in `3.8.0`.

- https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.8.0.html#removal-of-deprecated-apis

> The following deprecated APIs have been removed. Unless a replacement is stated, please vendor the previous implementation if needed.
> ...
> - The error_msg_gtk function and the icon_filename and window_icon globals in backend_gtk3; the error_msg_wx function in backend_wx

### PR DESCRIPTION
**Pull request by srmainwaring**
Fixes #1304 

Remove deprecated and unused imports from the macOS `wx` backend.

Summary of deprecated APIs:

- https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.8.0.html#removal-of-deprecated-apis

Tested with `matplotlib==3.7.4` for backwards compatibility and `matplotlib==3.8.2`.

### CODE REVIEW

**Comment by peterbarker** [comment]
Merged, thanks!
